version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/search_shops
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file: 
      - .env
    
  db:
    image: postgres:12-alpine
    env_file: 
      - .env

    ports:
      - 5432:5432
      
volumes:
  postgres_data: